[tool.poetry]
name = "audiblelight"
version = "0.1.0"
description = "A library for soundscape synthesis using spatial impulse responses derived from ray-traced room scans"
authors = ["Huw Cheston <h.cheston@qmul.ac.uk>", "Iran Roman <i.roman@qmul.ac.uk>"]
license = "CC-BY-4.0"
homepage = "https://github.com/AudibleLight/AudibleLight"
repository = "https://github.com/AudibleLight/AudibleLight"
keywords = ["audio", "sound", "soundscape", "environmental", "ambisonics", "microphone array", "sound event detection", "localization"]
classifiers = [
    "Programming Language :: Python",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Multimedia :: Sound/Audio :: Analysis",
    "Topic :: Multimedia :: Sound/Audio :: Sound Synthesis"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
librosa = "0.11.0"
soundfile = "*"
matplotlib = "*"
numpy = "2.0.2"
pandas = "2.2.2"
pillow = "11.2.1"
plotly = "5.24.1"
scipy = "*"
rtree = "1.4.0"
tqdm = "4.67.1"
trimesh = "4.6.11"
torch = "*"
loguru = "*"
pyroomacoustics = "*"
deepdiff = "*"
rlr-audio-propagation = { git = "https://github.com/AudibleLight/rlr-audio-propagation", branch = "main" }
pedalboard = "0.9.17"

[tool.poetry.group.dev.dependencies]
pytest = "*"
coverage = "*"
pytest-cov = "*"
pytest-xdist = "*"
pytest-rerunfailures = "*"
pytest-random-order = "*"
pre-commit = "*"
black = "24.4.2"
isort = "5.13.2"
flake8 = "7.0.0"

[tool.poetry.group.datasets.dependencies]
soundata = "*"
requests = "*"

[tool.poetry.group.docs.dependencies]
IPython = "*"
notebook = "^7.4.5"
sphinx = "*"
sphinx-book-theme = "*"
nbsphinx = "*"
myst-parser = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"