name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  REMOTE: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
#      - name: Run pre-commit checks
#        run: |
#          pip install pre-commit
#          pre-commit run --all-files -v
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt install libsox-dev freeglut3-dev
      - name: Test with unittest
        run: |
          python -m unittest discover tests