name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  REMOTE: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt install libsox-dev libsox-fmt-all freeglut3-dev
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -n auto -vv --cov-report term-missing --cov-report=xml --cov=audiblelight tests
