name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  REMOTE: true
  PYTHONMALLOC: debug
  MALLOC_CHECK_: "3"
  MALLOC_PERTURB_: ${{ github.run_id }}
  OMP_NUM_THREADS: "1"
  MKL_NUM_THREADS: "1"
  OPENBLAS_NUM_THREADS: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Add Poetry to PATH
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install system dependencies
        run: |
          make install

      - name: Style check + run tests
        run: |
          make tests

      - name: Upload coverage to Codecov
        if: success() && matrix.python-version == '3.12'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
